### ISSUE TITLE
REPORTE DE PRACTICA 8

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-danonino-programmers#1]
https://drive.google.com/file/d/1bbOwYoJAtEfmDOYGdY8_aZNrt-nuGxKH/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
18.8 puntos

Checar bien los requisitos en la portada y nos falto 1 figura para las 20 además que su tabla de figuras queda fuera de orden

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
